{% set version = "0.0.3" %}

package:
  name: particula
  version: {{ version }}

source:
  url: https://github.com/uncscode/particula/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91cacd9a54e5914335224f7022dbc17bc919e769f7735afac578dd6fdc05f489

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pint

test:
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -c "import particula; print(particula.__version__)"

about:
  home: https://github.com/uncscode/particula
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a simple, fast, and powerful particle simulator

extra:
  recipe-maintainers:
    - ngam
